### ISSUE TITLE
TODO v0.4

### ISSUE THREAD

**Issue by liquidcarbon** [liquidcarbon/affinity#2]
- [x] rewrote class factories to allow for type hinting

![image](https://github.com/user-attachments/assets/f0b0ee9a-34ab-4a89-a059-22ac07b3d567)

- [x] make [DuckDB v1.1 happy](https://github.com/duckdb/duckdb/issues/14179)
- [x] LOCATION attribute for partitioning and saving
- [x] `af.Dataset.partition()` yields lists of formatted paths and partitioned datasets 

Not done:
- add `flatten` for nested datasets - unclear how to organize this
- add `__annotations__` - this does not help IDE type hints; the
